manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ruslanch
      url-base: https://github.com/ruslanch
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-component-raytac-dongle
      remote: ruslanch
      revision: main
  self:
    path: config
